- config/routes.rb
Please check my routes migration
> added routes on top of devise

- app/controllers/pads_controller.rb
- test/controllers/pads_controller_test.rb
Please check my pads controller (empty)
> added empty pads controller

- app/controllers/bookings_controller.rb
- test/controllers/bookings_controller_test.rb
Created an empty bookings controllers in order to start working on it
> Creating an empty bookings controller to start working on it

- app/controllers/pets_controller.rb
- test/controllers/pets_controller_test.rb
> added empty pets controller

- Gemfile
- Gemfile.lock
- app/views/pages/home.html.erb
- db/seeds.rb
I finally finished the seed.rb file without the pictures. (there is a link at the bottom for random pics)
in order to use the seed file you must:
'gem install faker' in terminal
Write ' gem "faker" ' in your Gemfile, then bundle install
> Seed.rb done (without picture)

- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
just created an empty view, and the methods on bookings controller
>  Creating the bookings controller and an empty new view for booking

- app/controllers/pads_controller.rb
- app/models/booking.rb
- app/models/pad.rb
- app/models/pet.rb
Added validations to pet, pad, booking, user models!
> Added validations to pet, user, pad, booking models

- db/seeds.rb
Turns out you must edit the file in any small way otherwise you can't push files with no changes.
This should be the clean code checked by Laura and Noemi
> Seeds.rb (This is the improved one

- app/views/pads/show.html.erb
> added show view

- app/views/pads/show.html.erb
> Show action view

- app/controllers/bookings_controller.rb
- app/controllers/pads_controller.rb
- app/models/booking.rb
- app/views/bookings/new.html.erb
> cheked the booking form

- app/controllers/bookings_controller.rb
- config/routes.rb
create a booking send to the list of bookings
>  redirecting to see all bookings

- app/views/pads/show.html.erb
added paws ratings and added pads path to the show page for pads
> added paw ratings and padpath to show

- app/views/bookings/new.html.erb
Back button and calendar(daate picker)
> Back button and calendar(daate picker)

- app/views/bookings/index.html.erb
now we can go to the main page
> added the back button on index bookig

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/pads_controller.rb
- app/inputs/currency_input.rb
- app/policies/pad_policy.rb
- app/views/bookings/new.html.erb
- app/views/pads/index.html.erb
- app/views/pads/new.html.erb
- app/views/pads/show.html.erb
- app/views/shared/_navbar.html.erb
FYI also had to change show page so it would work for folks who've just listed a new pad — still plenty to do on this, but at least it's working for now!
> New pad path

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_price-circle.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/pads_controller.rb
- app/javascript/controllers/map_controller.js
- app/views/pads/_info_window.html.erb
- app/views/pads/index.html.erb
- app/views/pads/show.html.erb
- config/routes.rb
- db/schema.rb
- package.json
- yarn.lock
Styled the map and index page incl location search on the map and some popup silliness
> Index styling

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_price-circle.scss
- app/assets/stylesheets/pages/_show.scss
- app/controllers/pads_controller.rb
- app/javascript/controllers/map_controller.js
- app/models/pad.rb
- app/views/pads/_info_window.html.erb
- app/views/pads/index.html.erb
- app/views/pads/new.html.erb
- app/views/pads/show.html.erb
- config/routes.rb
- db/schema.rb
- package.json
- yarn.lock
> Updating new pads form

- app/controllers/bookings_controller.rb
- app/controllers/petsitter/bookings_controller.rb
- app/models/user.rb
- app/policies/booking_policy.rb
- app/policies/petsitter/booking_policy.rb
- app/views/petsitter/bookings/index.html.erb
- config/routes.rb
- test/controllers/petsitter/bookings_controller_test.rb
- test/policies/petsitter/booking_policy_test.rb
created the namespace and the empty view of petsitter bookings. Changed routes, booking controller petsitter_controller and policies
> created the namespace and the empty view of petsitter bookings

- app/controllers/bookings_controller.rb
- app/controllers/petsitter/bookings_controller.rb
- app/models/user.rb
- app/views/petsitter/bookings/index.html.erb
- config/routes.rb
- db/schema.rb
start to create the status of the pad of the petsitter
> start to create the status of the pad of the petsitter

- app/assets/stylesheets/application.scss
- app/views/bookings/index.html.erb
- db/schema.rb
- db/seeds.rb
I changed the seeds so that Ander (my account) now lists a pad at the bottom of the page. So booking your own pad is perhaps possible
I also updated the bookings index page so that it reflects most of the information on pads that sam edited.
> Bookingindex2

- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/profiles_controller.rb
- app/policies/profile_policy.rb
- app/views/pages/user_profile.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- test/controllers/profiles_controller_test.rb
- test/controllers/users_controller_test.rb
Created a profiles controller but turns out I didn't need it - the pages controller sufficed (and current_user)
> Navbar links to bookings index for petsitter and pet owner

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_homepage.scss
- app/assets/stylesheets/pages/_home.scss
- app/controllers/bookings_controller.rb
- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
> Landingpage
